### ISSUE TITLE
unoconv error

### ISSUE THREAD

**Issue by geraintou** [eprints/coversheets#1]
Thanks for the ingredient. When trying to add a coversheet to a document I'm getting:

unoconv: UnoException during export phase:
Unable to store document to file:///tmp/ep-coversheetLJpA/frontfile.pdf (Error (com.sun.star.io.IOException){ (com.sun.star.uno.Exception){ Message = (string)"SfxBaseModel::impl_store <file:///tmp/ep-coversheetLJpA/frontfile.pdf> failed: 0x4c0c(Error Area:Sfx Class:Write Code:12) /builddir/build/BUILD/libreoffice-7.1.8.1/sfx2/source/doc/sfxbasemodel.cxx:3153 /builddir/build/BUILD/libreoffice-7.1.8.1/sfx2/source/doc/sfxbasemodel.cxx:1735", Context = (com.sun.star.uno.XInterface)0x0{} } })

Properties: ((com.sun.star.beans.PropertyValue){ Name = (string)"FilterName", Handle = (long)0x0, Value = (any){ (string)"writer_pdf_Export" }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"OutputStream", Handle = (long)0x0, Value = (any){ (com.sun.star.uno.XInterface)0x563613cf7f58{, supportedInterfaces={com.sun.star.io.XOutputStream,com.sun.star.lang.XTypeProvider}} }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE }, (com.sun.star.beans.PropertyValue){ Name = (string)"Overwrite", Handle = (long)0x0, Value = (any){ (boolean)true }, State = (com.sun.star.beans.PropertyState)DIRECT_VALUE })

Any hints on how to resolve this?

Thanks

Geraint

**Comment by geraintou** [comment]
Thanks for the tips. Didn't resolve it unfortunately. This is on RHEL9 if that makes any difference

**Comment by drn05r** [comment]
Did you make sure the directory existed and was usable by the EPrints user.  Did the error message you see change from `/tmp/...` to `/opt/eprints3/tmp/...`?  As this is run from the command line it may pick up the temporary directory differently.  I will see if that is the case.

**Comment by drn05r** [comment]
I don't have a RHEL 9 server to test this on but I do have Rocky Linux 9, which is much the same.  When I get a chance (probably not today) , I will see if I can reproduce this issue.  

Do you have SELinux enabled on this server? You may need to add some rules to allow this.  However, an initial test would be to temporarily disable SELinux and see if coversheeting then works.  

Another issue that the unoconv command being run by the script is incorrect, which unoconv command to run is determined in `bin/check_coversheets`  It may be worth uncomment the two lines in this file that start:
````
#print STDERR "Coversheet invocation: 
````
Then compare this command to what you were running when you ran unoconv directly from the command line.

**Comment by geraintou** [comment]
Well that seems to have gone but now I'm getting:

dataset document has no field: coverdata_hash

------------------------------------------------------------------
----------- EPrints System Error 2024-04-29T11:19:21Z ------------
------------------------------------------------------------------
Attempt to get value from not existent field: document/coverdata_hash
------------------------------------------------------------------
EPrints System Error inducing stack dump
 at /opt/eprints/ingredients/coversheets/bin/../../../perl_lib/EPrints.pm line 163.
        EPrints::abort() called at /opt/eprints/ingredients/coversheets/bin/../../../perl_lib/EPrints/DataObj.pm line 1081
        EPrints::DataObj::get_value(EPrints::DataObj::Document=HASH(0x5636b64a42f8), "coverdata_hash") called at (eval 403) line 73
        EPrints::Config::oro::__ANON__("dataobj", EPrints::DataObj::EPrint=HASH(0x5636b64a1ed0), "repository", EPrints::Repository=HASH(0x5636aae6e1f8), "dataset", EPrints::DataSet=HASH(0x5636affc57a0), "changed", HASH(0x5636b649ca48)) called at /opt/eprints/ingredients/coversheets/bin/../../../perl_lib/EPrint


I don't have this field in the document table? Should I add ite?

**Comment by geraintou** [comment]
Digging into the documents folder it has created a pdf with a coversheet though

**Comment by drn05r** [comment]
I would make sure you run `/opt/eprints/bin/epadmin update ARCHIVE_ID`.  I assume you have added both the `coversheets` and `openoffice` ingredient to you inc file (e.g. `/opt/eprints/flavours/pub_lib/inc`)?  If you have an old version of coversheets that have configuration files in your archive's `cfg/cfg.d/` directory that override them you will need to remove these unless you have made local modification or reconcile them with the changes since the old version in the ingredients' version of these config files.  You should really only need `z_coversheet_tags.pl` at an archive level if any files at all.

**Comment by geraintou** [comment]
It seems like it actually working even with that unoconv error. I can use add_coversheet to add to a doc, and remove_coversheets also works as advertised. I'll implement it on another test server and see what happens. I've also setup libreoffice to run as a service

**Comment by drn05r** [comment]
Yes.  I have spotted that `add_coversheets` often if not always display a concerning message but the document still gets coversheeted.  I have been working on improving the README for this GitHub repo to explain how and when to use the scripts but have not had chance to complete this and push it back.  

Typically you would want to run `check_coversheets` as a regular cron.  In fact better still use `check_coversheets_cron` as this is an envelope script that ensure two instances of `check_coversheets` are not running at the same time.

**Comment by geraintou** [comment]
Thanks for adding the documentation, it really clarifies usage. Now to just work out how to get the license information from the document onto the coverpage with the tags file
